version: "3.8" # Specify the version of Docker Compose

services:
  app:
    build:
      context: . # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Name of the Dockerfile (optional if named Dockerfile)
    ports:
      - "7188:7188" # Map port 80 in the container to port 8080 on the host