# Generated by Django 2.1.7 on 2019-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20190816_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Fourth', 'Fourth'), ('Third', 'Third'), ('First', 'First'), ('Second', 'Second')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr'), ('Mr.', 'Mr'), ('Mrs.', 'Mrs'), ('Dr.', 'Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Fourth', 'Fourth'), ('Third', 'Third'), ('First', 'First'), ('Second', 'Second')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aff_type',
            field=models.CharField(choices=[('Visiting', 'Visiting'), ('Contract', 'Contract'), ('Permanent', 'Permanent')], default='Permanent', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr'), ('Mr.', 'Mr'), ('Mrs.', 'Mrs'), ('Dr.', 'Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors')], default='MSc', max_length=30),
        ),
    ]
