# Generated by Django 2.1.7 on 2019-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20190818_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Fourth', 'Fourth'), ('Third', 'Third'), ('Second', 'Second'), ('First', 'First')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr'), ('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr'), ('Mrs.', 'Mrs')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Diploma', 'Diploma'), ('PhD', 'PhD')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Fourth', 'Fourth'), ('Third', 'Third'), ('Second', 'Second'), ('First', 'First')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr'), ('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr'), ('Mrs.', 'Mrs')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Diploma', 'Diploma'), ('PhD', 'PhD')], default='MSc', max_length=30),
        ),
    ]
