# Generated by Django 2.1.7 on 2019-08-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20190823_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Fourth', 'Fourth'), ('Second', 'Second'), ('First', 'First'), ('Third', 'Third')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr'), ('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr'), ('Mrs.', 'Mrs')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors'), ('PhD', 'PhD')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Fourth', 'Fourth'), ('Second', 'Second'), ('First', 'First'), ('Third', 'Third')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aff_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Visiting', 'Visiting'), ('Contract', 'Contract')], default='Permanent', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr'), ('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr'), ('Mrs.', 'Mrs')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors'), ('PhD', 'PhD')], default='MSc', max_length=30),
        ),
    ]
