# Generated by Django 2.1.7 on 2023-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_auto_20190823_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='supervisor',
            field=models.ManyToManyField(to='college.Teacher'),
        ),
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Fourth', 'Fourth'), ('Third', 'Third'), ('First', 'First'), ('Second', 'Second')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Prof Dr.', 'Prof Dr'), ('Mrs.', 'Mrs'), ('Mr.', 'Mr'), ('Dr.', 'Dr'), ('Ms.', 'Ms')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('PhD', 'PhD'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Fourth', 'Fourth'), ('Third', 'Third'), ('First', 'First'), ('Second', 'Second')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Prof Dr.', 'Prof Dr'), ('Mrs.', 'Mrs'), ('Mr.', 'Mr'), ('Dr.', 'Dr'), ('Ms.', 'Ms')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='started_teaching',
            field=models.CharField(blank=True, default='2080', max_length=4, verbose_name='started teaching in BS'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('PhD', 'PhD'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(default='2080', max_length=40, unique=True),
        ),
    ]
