# Generated by Django 2.1.7 on 2023-08-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_auto_20230806_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Fourth', 'Fourth'), ('First', 'First'), ('Third', 'Third'), ('Second', 'Second')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs'), ('Prof Dr.', 'Prof Dr'), ('Ms.', 'Ms'), ('Mr.', 'Mr'), ('Dr.', 'Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Masters', 'Masters')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Fourth', 'Fourth'), ('First', 'First'), ('Third', 'Third'), ('Second', 'Second')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aff_type',
            field=models.CharField(choices=[('Contract', 'Contract'), ('Permanent', 'Permanent'), ('Visiting', 'Visiting')], default='Permanent', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs'), ('Prof Dr.', 'Prof Dr'), ('Ms.', 'Ms'), ('Mr.', 'Mr'), ('Dr.', 'Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Masters', 'Masters')], default='MSc', max_length=30),
        ),
    ]
