# Generated by Django 2.1.7 on 2023-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20230813_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Third', 'Third'), ('First', 'First'), ('Second', 'Second'), ('Fourth', 'Fourth')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs'), ('Mr.', 'Mr'), ('Dr.', 'Dr'), ('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors'), ('PhD', 'PhD')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Third', 'Third'), ('First', 'First'), ('Second', 'Second'), ('Fourth', 'Fourth')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aff_type',
            field=models.CharField(choices=[('Visiting', 'Visiting'), ('Contract', 'Contract'), ('Permanent', 'Permanent')], default='Permanent', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs'), ('Mr.', 'Mr'), ('Dr.', 'Dr'), ('Ms.', 'Ms'), ('Prof Dr.', 'Prof Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors'), ('PhD', 'PhD')], default='MSc', max_length=30),
        ),
    ]
