# Generated by Django 2.1.7 on 2023-08-16 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_auto_20230813_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='programme',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.Teacher'),
        ),
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Third', 'Third'), ('Second', 'Second'), ('First', 'First'), ('Fourth', 'Fourth')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr'), ('Ms.', 'Ms'), ('Mr.', 'Mr'), ('Mrs.', 'Mrs')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Bachelors', 'Bachelors'), ('PhD', 'PhD'), ('Masters', 'Masters')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Third', 'Third'), ('Second', 'Second'), ('First', 'First'), ('Fourth', 'Fourth')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aff_type',
            field=models.CharField(choices=[('Contract', 'Contract'), ('Permanent', 'Permanent'), ('Visiting', 'Visiting')], default='Permanent', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr'), ('Ms.', 'Ms'), ('Mr.', 'Mr'), ('Mrs.', 'Mrs')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Bachelors', 'Bachelors'), ('PhD', 'PhD'), ('Masters', 'Masters')], default='MSc', max_length=30),
        ),
    ]
