# Generated by Django 2.1.7 on 2024-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_auto_20240718_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubjectteacher',
            name='semester',
            field=models.CharField(choices=[('Fourth', 'Fourth'), ('Third', 'Third'), ('First', 'First'), ('Second', 'Second')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms'), ('Mrs.', 'Mrs'), ('Mr.', 'Mr'), ('Dr.', 'Dr'), ('Prof Dr.', 'Prof Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expert',
            name='upper_degree',
            field=models.CharField(choices=[('Masters', 'Masters'), ('Diploma', 'Diploma'), ('PhD', 'PhD'), ('Bachelors', 'Bachelors')], default='MSc', max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(blank=True, choices=[('Fourth', 'Fourth'), ('Third', 'Third'), ('First', 'First'), ('Second', 'Second')], max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aff_type',
            field=models.CharField(choices=[('Contract', 'Contract'), ('Permanent', 'Permanent'), ('Visiting', 'Visiting')], default='Permanent', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms'), ('Mrs.', 'Mrs'), ('Mr.', 'Mr'), ('Dr.', 'Dr'), ('Prof Dr.', 'Prof Dr')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upper_degree',
            field=models.CharField(choices=[('Masters', 'Masters'), ('Diploma', 'Diploma'), ('PhD', 'PhD'), ('Bachelors', 'Bachelors')], default='MSc', max_length=30),
        ),
    ]
